const REPO="rakatashraf/lupus-cortexdata";
const START="<!-- EARTHDATA_JOB_JSON_START -->";
const END="<!-- EARTHDATA_JOB_JSON_END -->";
const $=id=>document.getElementById(id);
const list=value=>value.split(/[;,\n]+/).map(v=>v.trim()).filter(Boolean);

function today(){
  const d=new Date();
  return d.toISOString().slice(0,10);
}
$("start").value=today();
$("end").value=today();

$("jobForm").addEventListener("submit",event=>{
  event.preventDefault();
  const components=list($("components").value);
  const collections=list($("collections").value);
  if(!components.length||!collections.length){
    $("status").textContent="Add at least one component and one collection ID.";
    return;
  }

  const config={
    components,
    collection_ids:collections,
    bbox:{
      south:Number($("south").value),
      west:Number($("west").value),
      north:Number($("north").value),
      east:Number($("east").value)
    },
    start_date:$("start").value,
    end_date:$("end").value,
    fallback_latest:$("fallback").checked,
    strict_component:$("strict").checked,
    include_ground:$("ground").checked,
    low_bandwidth_training_mode:$("compact").checked,
    workers:Number($("workers").value||8),
    output_name:$("output").value.trim()||"lupus_cortex_training.csv"
  };

  const title="[Earthdata Job] "+components.join("+")+" "+config.start_date+" to "+config.end_date;
  const body=[
    "## Lupus Cortex Earthdata processing job",
    "",
    "This issue was generated by the GitHub-hosted downloader UI.",
    "Do not place NASA credentials in this issue. The workflow reads the repository secret `EARTHDATA_TOKEN`.",
    "",
    START,
    "```json",
    JSON.stringify(config,null,2),
    "```",
    END,
    "",
    "Submitting this issue starts the GitHub Actions conversion workflow. The workflow will comment with the artifact/run link when processing completes."
  ].join("\n");

  const url="https://github.com/"+REPO+"/issues/new?title="+encodeURIComponent(title)+"&body="+encodeURIComponent(body);
  $("status").textContent="Opening GitHub. Submit the pre-filled issue to start processing.";
  window.open(url,"_blank","noopener,noreferrer");
});
